export const navRoutes = {
  START_UP: "START_UP",
  LOADING_STARTED: "LOADING_STARTED",
  INFO: "INFO",
  FACEBOOK:"FACEBOOK",
  ABOUT:"ABOUT",
  BAKONG:"BAKONG",
  WING:"WING",
  YOUTUBE:"YOUTUBE",


  LOGIN: "LOGIN",
  SIGNUP: "SIGNUP",
  NOTIFICATION: "NOTIFICATION",
  GUIDE: "GUIDE",
  TERMOfUSE: "TERMOfUSE",
  FORM: "FORM",
  FORM_SEASONAL: "FORM_SEASONAL",
  CARD: "CARD",
  CARD_SEASONAL: "CARD_SEASONAL",


  MAIN: "MAIN",
  HOME: "HOME",

  CORE: "CORE",
  PROFILE:"PROFILE",
  PROFILE_SEASONAL:"PROFILE_SEASONAL",

  DRAWER: "DRAWER",
};
